
CREATE TABLE TCU_FORNECEDOR_INABILITADO
   (	"CPF" VARCHAR2(20 BYTE), 
	"NOME" VARCHAR2(150 BYTE), 
	"UF" VARCHAR2(150 BYTE), 
	"MUNICIPIO" VARCHAR2(150 BYTE)
    "PROCESSO" VARCHAR2(70 BYTE), 
	"DELIBERACAO" VARCHAR2(20 BYTE), 
	"TRANSITO_JULGADO" VARCHAR2(20 BYTE), 
	"DATA_ACORDAO" VARCHAR2(20 BYTE), 
	"DATA_FINAL" VARCHAR2(50 BYTE), 
   ) ;


CREATE TABLE TCU_FORNECEDOR_INIDONEO 
   (	"CNPJ_CPF" VARCHAR2(40 BYTE), 
	"NOME" VARCHAR2(150 BYTE), 
	"UF" VARCHAR2(150 BYTE)
        "PROCESSO" VARCHAR2(70 BYTE), 
	"DELIBERACAO" VARCHAR2(20 BYTE), 
	"TRANSITO_JULGADO" VARCHAR2(20 BYTE), 
	"DATA_ACORDAO" VARCHAR2(20 BYTE), 
	"DATA_FINAL" VARCHAR2(50 BYTE), 
   ) ;
